### ISSUE TITLE
Problem creating vacation_type redmine 3.3

### ISSUE THREAD

**Issue by pablodav** [quanta-computing/redmine-marcel#2]
I got this problems: 

```
App 15166 stderr: Completed 200 OK in 21ms (Views: 16.0ms | ActiveRecord: 2.1ms)
App 15166 stderr: Started POST "/vacation_types" for 10.100.64.75 at 2017-01-28 00:15:34 -0300
App 15166 stderr: Processing by VacationTypesController#create as HTML
App 15166 stderr:   Parameters: {"utf8"=>"\u2713", "authenticity_token"=>"uud15T19nuNjiZ9vCDBXsKpEQQ9qwm5LvLY5ArIgKkMmCPs/HejH/52cdQri8L8MrzqvVKbtD+ZACsamKmKCfA==", "vacation_type"=>{"name"=>"ffffeee", "use_paid_vacation_days"=>"1", "use_recup_days"=>"0", "use_eating_tickets"=>"0"}, "commit"=>"Create Vacation type"}
App 15166 stderr:   Current user: admin (id=1)
App 15166 stderr: Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.4ms)
App 15166 stderr:
App 15166 stderr: ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
App 15166 stderr:   plugins/marcel/app/controllers/vacation_types_controller.rb:21:in `create'
App 15166 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

My redmine installation is: 

```
Environment:
  Redmine version                3.3.2.stable.16270
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  progressive_projects_list      3.0.1
  redmine_code_review            0.8.0
  redmine_custom_reports         0.1.5
  redmine_evm                    1.0.0
  redmine_gitlab_hook            0.1.3
  redmine_graphs                 0.1.0
  redmine_issue_template         1.0.7
  redmine_monitoring_controlling 0.1.1
  redmine_summed_fields          1.0.1
  redmine_workload               1.0.4
  sidebar_hide                   0.0.8
```

Hope this report could help in some way.

**Comment by Korrigan** [comment]
Hi @pablodav 

Thanks for the report! We're using this module with an old redmine version and to be honest I don't plan to upgrade our redmine installation for now and I don't have the time to troubleshoot this.

I'll, however, be happy to review & merge a PR which fix this if you have some spare time to dig into the issue :)

Best regards
